syntax = "proto3";

import "google/protobuf/empty.proto";

package manager;

option go_package = "github.com/Part001-R/YaPr-GP-2/proto";

service PasswordManager {
    rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);

    rpc BackupFile(stream UploadRequest) returns (UploadResponse);
    rpc RestoreFile(DownloadRequest) returns (stream DownloadResponse);
    rpc FilesInfo(google.protobuf.Empty) returns (FilesInfoResponse);

    rpc Registration(RegistrationRequest) returns (google.protobuf.Empty);
    rpc Authentication(AuthenticationRequest) returns (AuthenticationResponse);
    rpc SendLoginPassword(SendLoginPasswordRequest) returns (google.protobuf.Empty);
    rpc SendText(SendTextRequest) returns (google.protobuf.Empty);
    rpc SendBankCard(SendBankCardRequest) returns (google.protobuf.Empty);
    rpc SendFile(stream SendFileRequest) returns (SendFileResponse);
}

message UploadRequest {
    string fileName = 1;
    bytes content = 2;
}

message UploadResponse {
    string fileName = 1;
}

message DownloadRequest {
    string fileName = 1;
}

message DownloadResponse {
    string fileName = 1;
    bytes content = 2;
}

message FileInfo {
    string fileName = 1;
    int64 size = 2;
}

message FilesInfoResponse {
    repeated FileInfo fileInfo = 1;
}

message RegistrationRequest {
    string userName = 1;
    string userPwd = 2;
    string userPwdRepeat = 3;
}

message AuthenticationRequest {
    string userName = 1;
    string userPwd = 2;
}

message AuthenticationResponse {
    string token = 1;
}

message SendLoginPasswordRequest {
    string idClient = 1;
    string for = 2;
    string login = 3;
    string password = 4;
    string createdAt = 5;
}

message SendTextRequest {
    string idClient = 1;
    string for = 2;
    string text = 3;
    string createdAt = 4;
}

message SendBankCardRequest {
    string idClient = 1;
    string for = 2;
    string owner = 3;
    string numb = 4;
    string validData = 5;
    string code = 6;
    string createdAt = 7;
}

message SendFileRequest {
    string idClient = 1;
    string fileName = 2;
    bytes content = 3;
}

message SendFileResponse {
    string fileName = 1;
}
