// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalBackupFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalBackupFileRequest) Reset() {
	*x = LocalBackupFileRequest{}
	mi := &file_proto_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalBackupFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalBackupFileRequest) ProtoMessage() {}

func (x *LocalBackupFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalBackupFileRequest.ProtoReflect.Descriptor instead.
func (*LocalBackupFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{0}
}

func (x *LocalBackupFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LocalBackupFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LocalBackupFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalBackupFileResponse) Reset() {
	*x = LocalBackupFileResponse{}
	mi := &file_proto_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalBackupFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalBackupFileResponse) ProtoMessage() {}

func (x *LocalBackupFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalBackupFileResponse.ProtoReflect.Descriptor instead.
func (*LocalBackupFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{1}
}

func (x *LocalBackupFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type LocalRestoreFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRestoreFileRequest) Reset() {
	*x = LocalRestoreFileRequest{}
	mi := &file_proto_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRestoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRestoreFileRequest) ProtoMessage() {}

func (x *LocalRestoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRestoreFileRequest.ProtoReflect.Descriptor instead.
func (*LocalRestoreFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{2}
}

func (x *LocalRestoreFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type LocalRestoreFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalRestoreFileResponse) Reset() {
	*x = LocalRestoreFileResponse{}
	mi := &file_proto_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalRestoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRestoreFileResponse) ProtoMessage() {}

func (x *LocalRestoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRestoreFileResponse.ProtoReflect.Descriptor instead.
func (*LocalRestoreFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{3}
}

func (x *LocalRestoreFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LocalRestoreFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{4}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LocalFilesInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileInfo      []*FileInfo            `protobuf:"bytes,1,rep,name=fileInfo,proto3" json:"fileInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalFilesInfoResponse) Reset() {
	*x = LocalFilesInfoResponse{}
	mi := &file_proto_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalFilesInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFilesInfoResponse) ProtoMessage() {}

func (x *LocalFilesInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFilesInfoResponse.ProtoReflect.Descriptor instead.
func (*LocalFilesInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{5}
}

func (x *LocalFilesInfoResponse) GetFileInfo() []*FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPwd       string                 `protobuf:"bytes,2,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	UserPwdRepeat string                 `protobuf:"bytes,3,opt,name=userPwdRepeat,proto3" json:"userPwdRepeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_proto_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{6}
}

func (x *RegistrationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegistrationRequest) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *RegistrationRequest) GetUserPwdRepeat() string {
	if x != nil {
		return x.UserPwdRepeat
	}
	return ""
}

type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPwd       string                 `protobuf:"bytes,2,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_proto_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AuthenticationRequest) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

type AuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_proto_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{8}
}

func (x *AuthenticationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SendLoginPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClient      string                 `protobuf:"bytes,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	For           string                 `protobuf:"bytes,2,opt,name=for,proto3" json:"for,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLoginPasswordRequest) Reset() {
	*x = SendLoginPasswordRequest{}
	mi := &file_proto_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLoginPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLoginPasswordRequest) ProtoMessage() {}

func (x *SendLoginPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLoginPasswordRequest.ProtoReflect.Descriptor instead.
func (*SendLoginPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{9}
}

func (x *SendLoginPasswordRequest) GetIdClient() string {
	if x != nil {
		return x.IdClient
	}
	return ""
}

func (x *SendLoginPasswordRequest) GetFor() string {
	if x != nil {
		return x.For
	}
	return ""
}

func (x *SendLoginPasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SendLoginPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SendLoginPasswordRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SendTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClient      string                 `protobuf:"bytes,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	For           string                 `protobuf:"bytes,2,opt,name=for,proto3" json:"for,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_proto_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{10}
}

func (x *SendTextRequest) GetIdClient() string {
	if x != nil {
		return x.IdClient
	}
	return ""
}

func (x *SendTextRequest) GetFor() string {
	if x != nil {
		return x.For
	}
	return ""
}

func (x *SendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendTextRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SendBankCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClient      string                 `protobuf:"bytes,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	For           string                 `protobuf:"bytes,2,opt,name=for,proto3" json:"for,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Numb          string                 `protobuf:"bytes,4,opt,name=numb,proto3" json:"numb,omitempty"`
	ValidData     string                 `protobuf:"bytes,5,opt,name=validData,proto3" json:"validData,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBankCardRequest) Reset() {
	*x = SendBankCardRequest{}
	mi := &file_proto_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBankCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBankCardRequest) ProtoMessage() {}

func (x *SendBankCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBankCardRequest.ProtoReflect.Descriptor instead.
func (*SendBankCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{11}
}

func (x *SendBankCardRequest) GetIdClient() string {
	if x != nil {
		return x.IdClient
	}
	return ""
}

func (x *SendBankCardRequest) GetFor() string {
	if x != nil {
		return x.For
	}
	return ""
}

func (x *SendBankCardRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SendBankCardRequest) GetNumb() string {
	if x != nil {
		return x.Numb
	}
	return ""
}

func (x *SendBankCardRequest) GetValidData() string {
	if x != nil {
		return x.ValidData
	}
	return ""
}

func (x *SendBankCardRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendBankCardRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClient      string                 `protobuf:"bytes,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_proto_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{12}
}

func (x *SendFileRequest) GetIdClient() string {
	if x != nil {
		return x.IdClient
	}
	return ""
}

func (x *SendFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_proto_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{13}
}

func (x *SendFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type RequestLoginPasswordNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntriesName   []string               `protobuf:"bytes,1,rep,name=EntriesName,proto3" json:"EntriesName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLoginPasswordNameResponse) Reset() {
	*x = RequestLoginPasswordNameResponse{}
	mi := &file_proto_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLoginPasswordNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoginPasswordNameResponse) ProtoMessage() {}

func (x *RequestLoginPasswordNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoginPasswordNameResponse.ProtoReflect.Descriptor instead.
func (*RequestLoginPasswordNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{14}
}

func (x *RequestLoginPasswordNameResponse) GetEntriesName() []string {
	if x != nil {
		return x.EntriesName
	}
	return nil
}

type RequestLoginPasswordByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClient      string                 `protobuf:"bytes,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLoginPasswordByNameRequest) Reset() {
	*x = RequestLoginPasswordByNameRequest{}
	mi := &file_proto_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLoginPasswordByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoginPasswordByNameRequest) ProtoMessage() {}

func (x *RequestLoginPasswordByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoginPasswordByNameRequest.ProtoReflect.Descriptor instead.
func (*RequestLoginPasswordByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{15}
}

func (x *RequestLoginPasswordByNameRequest) GetIdClient() string {
	if x != nil {
		return x.IdClient
	}
	return ""
}

func (x *RequestLoginPasswordByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequestLoginPasswordByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestLoginPasswordByNameResponse) Reset() {
	*x = RequestLoginPasswordByNameResponse{}
	mi := &file_proto_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestLoginPasswordByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLoginPasswordByNameResponse) ProtoMessage() {}

func (x *RequestLoginPasswordByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLoginPasswordByNameResponse.ProtoReflect.Descriptor instead.
func (*RequestLoginPasswordByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{16}
}

func (x *RequestLoginPasswordByNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestLoginPasswordByNameResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RequestLoginPasswordByNameResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RequestLoginPasswordByNameResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RequestTextNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntriesName   []string               `protobuf:"bytes,1,rep,name=EntriesName,proto3" json:"EntriesName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTextNameResponse) Reset() {
	*x = RequestTextNameResponse{}
	mi := &file_proto_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTextNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTextNameResponse) ProtoMessage() {}

func (x *RequestTextNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTextNameResponse.ProtoReflect.Descriptor instead.
func (*RequestTextNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{17}
}

func (x *RequestTextNameResponse) GetEntriesName() []string {
	if x != nil {
		return x.EntriesName
	}
	return nil
}

type RequestTextByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClient      string                 `protobuf:"bytes,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTextByNameRequest) Reset() {
	*x = RequestTextByNameRequest{}
	mi := &file_proto_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTextByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTextByNameRequest) ProtoMessage() {}

func (x *RequestTextByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTextByNameRequest.ProtoReflect.Descriptor instead.
func (*RequestTextByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{18}
}

func (x *RequestTextByNameRequest) GetIdClient() string {
	if x != nil {
		return x.IdClient
	}
	return ""
}

func (x *RequestTextByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequestTextByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTextByNameResponse) Reset() {
	*x = RequestTextByNameResponse{}
	mi := &file_proto_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTextByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTextByNameResponse) ProtoMessage() {}

func (x *RequestTextByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTextByNameResponse.ProtoReflect.Descriptor instead.
func (*RequestTextByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_proto_rawDescGZIP(), []int{19}
}

func (x *RequestTextByNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestTextByNameResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RequestTextByNameResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_client_proto protoreflect.FileDescriptor

const file_proto_client_proto_rawDesc = "" +
	"\n" +
	"\x12proto/client.proto\x12\amanager\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x16LocalBackupFileRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"5\n" +
	"\x17LocalBackupFileResponse\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\"5\n" +
	"\x17LocalRestoreFileRequest\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\"P\n" +
	"\x18LocalRestoreFileResponse\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\":\n" +
	"\bFileInfo\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"G\n" +
	"\x16LocalFilesInfoResponse\x12-\n" +
	"\bfileInfo\x18\x01 \x03(\v2\x11.manager.FileInfoR\bfileInfo\"q\n" +
	"\x13RegistrationRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x18\n" +
	"\auserPwd\x18\x02 \x01(\tR\auserPwd\x12$\n" +
	"\ruserPwdRepeat\x18\x03 \x01(\tR\ruserPwdRepeat\"M\n" +
	"\x15AuthenticationRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x18\n" +
	"\auserPwd\x18\x02 \x01(\tR\auserPwd\".\n" +
	"\x16AuthenticationResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x98\x01\n" +
	"\x18SendLoginPasswordRequest\x12\x1a\n" +
	"\bidClient\x18\x01 \x01(\tR\bidClient\x12\x10\n" +
	"\x03for\x18\x02 \x01(\tR\x03for\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\"q\n" +
	"\x0fSendTextRequest\x12\x1a\n" +
	"\bidClient\x18\x01 \x01(\tR\bidClient\x12\x10\n" +
	"\x03for\x18\x02 \x01(\tR\x03for\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\"\xbd\x01\n" +
	"\x13SendBankCardRequest\x12\x1a\n" +
	"\bidClient\x18\x01 \x01(\tR\bidClient\x12\x10\n" +
	"\x03for\x18\x02 \x01(\tR\x03for\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x12\n" +
	"\x04numb\x18\x04 \x01(\tR\x04numb\x12\x1c\n" +
	"\tvalidData\x18\x05 \x01(\tR\tvalidData\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\"c\n" +
	"\x0fSendFileRequest\x12\x1a\n" +
	"\bidClient\x18\x01 \x01(\tR\bidClient\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\".\n" +
	"\x10SendFileResponse\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\"D\n" +
	" RequestLoginPasswordNameResponse\x12 \n" +
	"\vEntriesName\x18\x01 \x03(\tR\vEntriesName\"S\n" +
	"!RequestLoginPasswordByNameRequest\x12\x1a\n" +
	"\bidClient\x18\x01 \x01(\tR\bidClient\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x88\x01\n" +
	"\"RequestLoginPasswordByNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\";\n" +
	"\x17RequestTextNameResponse\x12 \n" +
	"\vEntriesName\x18\x01 \x03(\tR\vEntriesName\"J\n" +
	"\x18RequestTextByNameRequest\x12\x1a\n" +
	"\bidClient\x18\x01 \x01(\tR\bidClient\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"a\n" +
	"\x19RequestTextByNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\tcreatedAt\x18\x03 \x01(\tR\tcreatedAt2\xf6\b\n" +
	"\x0fPasswordManager\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x0fLocalBackupFile\x12\x1f.manager.LocalBackupFileRequest\x1a .manager.LocalBackupFileResponse(\x01\x12Y\n" +
	"\x10LocalRestoreFile\x12 .manager.LocalRestoreFileRequest\x1a!.manager.LocalRestoreFileResponse0\x01\x12I\n" +
	"\x0eLocalFilesInfo\x12\x16.google.protobuf.Empty\x1a\x1f.manager.LocalFilesInfoResponse\x12D\n" +
	"\fRegistration\x12\x1c.manager.RegistrationRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0eAuthentication\x12\x1e.manager.AuthenticationRequest\x1a\x1f.manager.AuthenticationResponse\x12N\n" +
	"\x11SendLoginPassword\x12!.manager.SendLoginPasswordRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\bSendText\x12\x18.manager.SendTextRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fSendBankCard\x12\x1c.manager.SendBankCardRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\bSendFile\x12\x18.manager.SendFileRequest\x1a\x19.manager.SendFileResponse(\x01\x12]\n" +
	"\x18RequestLoginPasswordName\x12\x16.google.protobuf.Empty\x1a).manager.RequestLoginPasswordNameResponse\x12u\n" +
	"\x1aRequestLoginPasswordByName\x12*.manager.RequestLoginPasswordByNameRequest\x1a+.manager.RequestLoginPasswordByNameResponse\x12K\n" +
	"\x0fRequestTextName\x12\x16.google.protobuf.Empty\x1a .manager.RequestTextNameResponse\x12Z\n" +
	"\x11RequestTextByName\x12!.manager.RequestTextByNameRequest\x1a\".manager.RequestTextByNameResponseB&Z$github.com/Part001-R/YaPr-GP-2/protob\x06proto3"

var (
	file_proto_client_proto_rawDescOnce sync.Once
	file_proto_client_proto_rawDescData []byte
)

func file_proto_client_proto_rawDescGZIP() []byte {
	file_proto_client_proto_rawDescOnce.Do(func() {
		file_proto_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)))
	})
	return file_proto_client_proto_rawDescData
}

var file_proto_client_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_client_proto_goTypes = []any{
	(*LocalBackupFileRequest)(nil),             // 0: manager.LocalBackupFileRequest
	(*LocalBackupFileResponse)(nil),            // 1: manager.LocalBackupFileResponse
	(*LocalRestoreFileRequest)(nil),            // 2: manager.LocalRestoreFileRequest
	(*LocalRestoreFileResponse)(nil),           // 3: manager.LocalRestoreFileResponse
	(*FileInfo)(nil),                           // 4: manager.FileInfo
	(*LocalFilesInfoResponse)(nil),             // 5: manager.LocalFilesInfoResponse
	(*RegistrationRequest)(nil),                // 6: manager.RegistrationRequest
	(*AuthenticationRequest)(nil),              // 7: manager.AuthenticationRequest
	(*AuthenticationResponse)(nil),             // 8: manager.AuthenticationResponse
	(*SendLoginPasswordRequest)(nil),           // 9: manager.SendLoginPasswordRequest
	(*SendTextRequest)(nil),                    // 10: manager.SendTextRequest
	(*SendBankCardRequest)(nil),                // 11: manager.SendBankCardRequest
	(*SendFileRequest)(nil),                    // 12: manager.SendFileRequest
	(*SendFileResponse)(nil),                   // 13: manager.SendFileResponse
	(*RequestLoginPasswordNameResponse)(nil),   // 14: manager.RequestLoginPasswordNameResponse
	(*RequestLoginPasswordByNameRequest)(nil),  // 15: manager.RequestLoginPasswordByNameRequest
	(*RequestLoginPasswordByNameResponse)(nil), // 16: manager.RequestLoginPasswordByNameResponse
	(*RequestTextNameResponse)(nil),            // 17: manager.RequestTextNameResponse
	(*RequestTextByNameRequest)(nil),           // 18: manager.RequestTextByNameRequest
	(*RequestTextByNameResponse)(nil),          // 19: manager.RequestTextByNameResponse
	(*emptypb.Empty)(nil),                      // 20: google.protobuf.Empty
}
var file_proto_client_proto_depIdxs = []int32{
	4,  // 0: manager.LocalFilesInfoResponse.fileInfo:type_name -> manager.FileInfo
	20, // 1: manager.PasswordManager.Ping:input_type -> google.protobuf.Empty
	0,  // 2: manager.PasswordManager.LocalBackupFile:input_type -> manager.LocalBackupFileRequest
	2,  // 3: manager.PasswordManager.LocalRestoreFile:input_type -> manager.LocalRestoreFileRequest
	20, // 4: manager.PasswordManager.LocalFilesInfo:input_type -> google.protobuf.Empty
	6,  // 5: manager.PasswordManager.Registration:input_type -> manager.RegistrationRequest
	7,  // 6: manager.PasswordManager.Authentication:input_type -> manager.AuthenticationRequest
	9,  // 7: manager.PasswordManager.SendLoginPassword:input_type -> manager.SendLoginPasswordRequest
	10, // 8: manager.PasswordManager.SendText:input_type -> manager.SendTextRequest
	11, // 9: manager.PasswordManager.SendBankCard:input_type -> manager.SendBankCardRequest
	12, // 10: manager.PasswordManager.SendFile:input_type -> manager.SendFileRequest
	20, // 11: manager.PasswordManager.RequestLoginPasswordName:input_type -> google.protobuf.Empty
	15, // 12: manager.PasswordManager.RequestLoginPasswordByName:input_type -> manager.RequestLoginPasswordByNameRequest
	20, // 13: manager.PasswordManager.RequestTextName:input_type -> google.protobuf.Empty
	18, // 14: manager.PasswordManager.RequestTextByName:input_type -> manager.RequestTextByNameRequest
	20, // 15: manager.PasswordManager.Ping:output_type -> google.protobuf.Empty
	1,  // 16: manager.PasswordManager.LocalBackupFile:output_type -> manager.LocalBackupFileResponse
	3,  // 17: manager.PasswordManager.LocalRestoreFile:output_type -> manager.LocalRestoreFileResponse
	5,  // 18: manager.PasswordManager.LocalFilesInfo:output_type -> manager.LocalFilesInfoResponse
	20, // 19: manager.PasswordManager.Registration:output_type -> google.protobuf.Empty
	8,  // 20: manager.PasswordManager.Authentication:output_type -> manager.AuthenticationResponse
	20, // 21: manager.PasswordManager.SendLoginPassword:output_type -> google.protobuf.Empty
	20, // 22: manager.PasswordManager.SendText:output_type -> google.protobuf.Empty
	20, // 23: manager.PasswordManager.SendBankCard:output_type -> google.protobuf.Empty
	13, // 24: manager.PasswordManager.SendFile:output_type -> manager.SendFileResponse
	14, // 25: manager.PasswordManager.RequestLoginPasswordName:output_type -> manager.RequestLoginPasswordNameResponse
	16, // 26: manager.PasswordManager.RequestLoginPasswordByName:output_type -> manager.RequestLoginPasswordByNameResponse
	17, // 27: manager.PasswordManager.RequestTextName:output_type -> manager.RequestTextNameResponse
	19, // 28: manager.PasswordManager.RequestTextByName:output_type -> manager.RequestTextByNameResponse
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_client_proto_init() }
func file_proto_client_proto_init() {
	if File_proto_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_proto_rawDesc), len(file_proto_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_proto_goTypes,
		DependencyIndexes: file_proto_client_proto_depIdxs,
		MessageInfos:      file_proto_client_proto_msgTypes,
	}.Build()
	File_proto_client_proto = out.File
	file_proto_client_proto_goTypes = nil
	file_proto_client_proto_depIdxs = nil
}
