// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/client.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PasswordManager_Ping_FullMethodName                       = "/manager.PasswordManager/Ping"
	PasswordManager_LocalBackupFile_FullMethodName            = "/manager.PasswordManager/LocalBackupFile"
	PasswordManager_LocalRestoreFile_FullMethodName           = "/manager.PasswordManager/LocalRestoreFile"
	PasswordManager_LocalFilesInfo_FullMethodName             = "/manager.PasswordManager/LocalFilesInfo"
	PasswordManager_Registration_FullMethodName               = "/manager.PasswordManager/Registration"
	PasswordManager_Authentication_FullMethodName             = "/manager.PasswordManager/Authentication"
	PasswordManager_SendLoginPassword_FullMethodName          = "/manager.PasswordManager/SendLoginPassword"
	PasswordManager_SendText_FullMethodName                   = "/manager.PasswordManager/SendText"
	PasswordManager_SendBankCard_FullMethodName               = "/manager.PasswordManager/SendBankCard"
	PasswordManager_SendFile_FullMethodName                   = "/manager.PasswordManager/SendFile"
	PasswordManager_RequestLoginPasswordName_FullMethodName   = "/manager.PasswordManager/RequestLoginPasswordName"
	PasswordManager_RequestLoginPasswordByName_FullMethodName = "/manager.PasswordManager/RequestLoginPasswordByName"
	PasswordManager_RequestTextName_FullMethodName            = "/manager.PasswordManager/RequestTextName"
	PasswordManager_RequestTextByName_FullMethodName          = "/manager.PasswordManager/RequestTextByName"
	PasswordManager_RequestBankCardName_FullMethodName        = "/manager.PasswordManager/RequestBankCardName"
	PasswordManager_RequestBankCardByName_FullMethodName      = "/manager.PasswordManager/RequestBankCardByName"
	PasswordManager_RequestFileName_FullMethodName            = "/manager.PasswordManager/RequestFileName"
	PasswordManager_RequestFileByName_FullMethodName          = "/manager.PasswordManager/RequestFileByName"
)

// PasswordManagerClient is the client API for PasswordManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasswordManagerClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LocalBackupFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocalBackupFileRequest, LocalBackupFileResponse], error)
	LocalRestoreFile(ctx context.Context, in *LocalRestoreFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocalRestoreFileResponse], error)
	LocalFilesInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LocalFilesInfoResponse, error)
	Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Authentication(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
	SendLoginPassword(ctx context.Context, in *SendLoginPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendBankCard(ctx context.Context, in *SendBankCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendFileRequest, SendFileResponse], error)
	RequestLoginPasswordName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestLoginPasswordNameResponse, error)
	RequestLoginPasswordByName(ctx context.Context, in *RequestLoginPasswordByNameRequest, opts ...grpc.CallOption) (*RequestLoginPasswordByNameResponse, error)
	RequestTextName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestTextNameResponse, error)
	RequestTextByName(ctx context.Context, in *RequestTextByNameRequest, opts ...grpc.CallOption) (*RequestTextByNameResponse, error)
	RequestBankCardName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestBankCardNameResponse, error)
	RequestBankCardByName(ctx context.Context, in *RequestBankCardByNameRequest, opts ...grpc.CallOption) (*RequestBankCardByNameResponse, error)
	RequestFileName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestFileNameResponse, error)
	RequestFileByName(ctx context.Context, in *RequestFileByNameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RequestFileByNameResponse], error)
}

type passwordManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPasswordManagerClient(cc grpc.ClientConnInterface) PasswordManagerClient {
	return &passwordManagerClient{cc}
}

func (c *passwordManagerClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) LocalBackupFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocalBackupFileRequest, LocalBackupFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[0], PasswordManager_LocalBackupFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocalBackupFileRequest, LocalBackupFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_LocalBackupFileClient = grpc.ClientStreamingClient[LocalBackupFileRequest, LocalBackupFileResponse]

func (c *passwordManagerClient) LocalRestoreFile(ctx context.Context, in *LocalRestoreFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LocalRestoreFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[1], PasswordManager_LocalRestoreFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocalRestoreFileRequest, LocalRestoreFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_LocalRestoreFileClient = grpc.ServerStreamingClient[LocalRestoreFileResponse]

func (c *passwordManagerClient) LocalFilesInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LocalFilesInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocalFilesInfoResponse)
	err := c.cc.Invoke(ctx, PasswordManager_LocalFilesInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_Registration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) Authentication(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, PasswordManager_Authentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendLoginPassword(ctx context.Context, in *SendLoginPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_SendLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendBankCard(ctx context.Context, in *SendBankCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_SendBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendFileRequest, SendFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[2], PasswordManager_SendFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendFileRequest, SendFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_SendFileClient = grpc.ClientStreamingClient[SendFileRequest, SendFileResponse]

func (c *passwordManagerClient) RequestLoginPasswordName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestLoginPasswordNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestLoginPasswordNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestLoginPasswordName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestLoginPasswordByName(ctx context.Context, in *RequestLoginPasswordByNameRequest, opts ...grpc.CallOption) (*RequestLoginPasswordByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestLoginPasswordByNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestLoginPasswordByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestTextName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestTextNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestTextNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestTextName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestTextByName(ctx context.Context, in *RequestTextByNameRequest, opts ...grpc.CallOption) (*RequestTextByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestTextByNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestTextByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestBankCardName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestBankCardNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestBankCardNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestBankCardName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestBankCardByName(ctx context.Context, in *RequestBankCardByNameRequest, opts ...grpc.CallOption) (*RequestBankCardByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestBankCardByNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestBankCardByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestFileName(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RequestFileNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestFileNameResponse)
	err := c.cc.Invoke(ctx, PasswordManager_RequestFileName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) RequestFileByName(ctx context.Context, in *RequestFileByNameRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RequestFileByNameResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[3], PasswordManager_RequestFileByName_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestFileByNameRequest, RequestFileByNameResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_RequestFileByNameClient = grpc.ServerStreamingClient[RequestFileByNameResponse]

// PasswordManagerServer is the server API for PasswordManager service.
// All implementations must embed UnimplementedPasswordManagerServer
// for forward compatibility.
type PasswordManagerServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	LocalBackupFile(grpc.ClientStreamingServer[LocalBackupFileRequest, LocalBackupFileResponse]) error
	LocalRestoreFile(*LocalRestoreFileRequest, grpc.ServerStreamingServer[LocalRestoreFileResponse]) error
	LocalFilesInfo(context.Context, *emptypb.Empty) (*LocalFilesInfoResponse, error)
	Registration(context.Context, *RegistrationRequest) (*emptypb.Empty, error)
	Authentication(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
	SendLoginPassword(context.Context, *SendLoginPasswordRequest) (*emptypb.Empty, error)
	SendText(context.Context, *SendTextRequest) (*emptypb.Empty, error)
	SendBankCard(context.Context, *SendBankCardRequest) (*emptypb.Empty, error)
	SendFile(grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]) error
	RequestLoginPasswordName(context.Context, *emptypb.Empty) (*RequestLoginPasswordNameResponse, error)
	RequestLoginPasswordByName(context.Context, *RequestLoginPasswordByNameRequest) (*RequestLoginPasswordByNameResponse, error)
	RequestTextName(context.Context, *emptypb.Empty) (*RequestTextNameResponse, error)
	RequestTextByName(context.Context, *RequestTextByNameRequest) (*RequestTextByNameResponse, error)
	RequestBankCardName(context.Context, *emptypb.Empty) (*RequestBankCardNameResponse, error)
	RequestBankCardByName(context.Context, *RequestBankCardByNameRequest) (*RequestBankCardByNameResponse, error)
	RequestFileName(context.Context, *emptypb.Empty) (*RequestFileNameResponse, error)
	RequestFileByName(*RequestFileByNameRequest, grpc.ServerStreamingServer[RequestFileByNameResponse]) error
	mustEmbedUnimplementedPasswordManagerServer()
}

// UnimplementedPasswordManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPasswordManagerServer struct{}

func (UnimplementedPasswordManagerServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPasswordManagerServer) LocalBackupFile(grpc.ClientStreamingServer[LocalBackupFileRequest, LocalBackupFileResponse]) error {
	return status.Error(codes.Unimplemented, "method LocalBackupFile not implemented")
}
func (UnimplementedPasswordManagerServer) LocalRestoreFile(*LocalRestoreFileRequest, grpc.ServerStreamingServer[LocalRestoreFileResponse]) error {
	return status.Error(codes.Unimplemented, "method LocalRestoreFile not implemented")
}
func (UnimplementedPasswordManagerServer) LocalFilesInfo(context.Context, *emptypb.Empty) (*LocalFilesInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LocalFilesInfo not implemented")
}
func (UnimplementedPasswordManagerServer) Registration(context.Context, *RegistrationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Registration not implemented")
}
func (UnimplementedPasswordManagerServer) Authentication(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authentication not implemented")
}
func (UnimplementedPasswordManagerServer) SendLoginPassword(context.Context, *SendLoginPasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLoginPassword not implemented")
}
func (UnimplementedPasswordManagerServer) SendText(context.Context, *SendTextRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedPasswordManagerServer) SendBankCard(context.Context, *SendBankCardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBankCard not implemented")
}
func (UnimplementedPasswordManagerServer) SendFile(grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]) error {
	return status.Error(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedPasswordManagerServer) RequestLoginPasswordName(context.Context, *emptypb.Empty) (*RequestLoginPasswordNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestLoginPasswordName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestLoginPasswordByName(context.Context, *RequestLoginPasswordByNameRequest) (*RequestLoginPasswordByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestLoginPasswordByName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestTextName(context.Context, *emptypb.Empty) (*RequestTextNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTextName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestTextByName(context.Context, *RequestTextByNameRequest) (*RequestTextByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTextByName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestBankCardName(context.Context, *emptypb.Empty) (*RequestBankCardNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestBankCardName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestBankCardByName(context.Context, *RequestBankCardByNameRequest) (*RequestBankCardByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestBankCardByName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestFileName(context.Context, *emptypb.Empty) (*RequestFileNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestFileName not implemented")
}
func (UnimplementedPasswordManagerServer) RequestFileByName(*RequestFileByNameRequest, grpc.ServerStreamingServer[RequestFileByNameResponse]) error {
	return status.Error(codes.Unimplemented, "method RequestFileByName not implemented")
}
func (UnimplementedPasswordManagerServer) mustEmbedUnimplementedPasswordManagerServer() {}
func (UnimplementedPasswordManagerServer) testEmbeddedByValue()                         {}

// UnsafePasswordManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasswordManagerServer will
// result in compilation errors.
type UnsafePasswordManagerServer interface {
	mustEmbedUnimplementedPasswordManagerServer()
}

func RegisterPasswordManagerServer(s grpc.ServiceRegistrar, srv PasswordManagerServer) {
	// If the following call panics, it indicates UnimplementedPasswordManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PasswordManager_ServiceDesc, srv)
}

func _PasswordManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_LocalBackupFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PasswordManagerServer).LocalBackupFile(&grpc.GenericServerStream[LocalBackupFileRequest, LocalBackupFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_LocalBackupFileServer = grpc.ClientStreamingServer[LocalBackupFileRequest, LocalBackupFileResponse]

func _PasswordManager_LocalRestoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LocalRestoreFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PasswordManagerServer).LocalRestoreFile(m, &grpc.GenericServerStream[LocalRestoreFileRequest, LocalRestoreFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_LocalRestoreFileServer = grpc.ServerStreamingServer[LocalRestoreFileResponse]

func _PasswordManager_LocalFilesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).LocalFilesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_LocalFilesInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).LocalFilesInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_Registration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).Registration(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_Authentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).Authentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_Authentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).Authentication(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLoginPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).SendLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_SendLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).SendLoginPassword(ctx, req.(*SendLoginPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBankCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).SendBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_SendBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).SendBankCard(ctx, req.(*SendBankCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PasswordManagerServer).SendFile(&grpc.GenericServerStream[SendFileRequest, SendFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_SendFileServer = grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]

func _PasswordManager_RequestLoginPasswordName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestLoginPasswordName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestLoginPasswordName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestLoginPasswordName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestLoginPasswordByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLoginPasswordByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestLoginPasswordByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestLoginPasswordByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestLoginPasswordByName(ctx, req.(*RequestLoginPasswordByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestTextName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestTextName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestTextName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestTextName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestTextByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTextByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestTextByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestTextByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestTextByName(ctx, req.(*RequestTextByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestBankCardName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestBankCardName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestBankCardName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestBankCardName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestBankCardByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBankCardByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestBankCardByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestBankCardByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestBankCardByName(ctx, req.(*RequestBankCardByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestFileName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).RequestFileName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_RequestFileName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).RequestFileName(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_RequestFileByName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestFileByNameRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PasswordManagerServer).RequestFileByName(m, &grpc.GenericServerStream[RequestFileByNameRequest, RequestFileByNameResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_RequestFileByNameServer = grpc.ServerStreamingServer[RequestFileByNameResponse]

// PasswordManager_ServiceDesc is the grpc.ServiceDesc for PasswordManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasswordManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager.PasswordManager",
	HandlerType: (*PasswordManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PasswordManager_Ping_Handler,
		},
		{
			MethodName: "LocalFilesInfo",
			Handler:    _PasswordManager_LocalFilesInfo_Handler,
		},
		{
			MethodName: "Registration",
			Handler:    _PasswordManager_Registration_Handler,
		},
		{
			MethodName: "Authentication",
			Handler:    _PasswordManager_Authentication_Handler,
		},
		{
			MethodName: "SendLoginPassword",
			Handler:    _PasswordManager_SendLoginPassword_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _PasswordManager_SendText_Handler,
		},
		{
			MethodName: "SendBankCard",
			Handler:    _PasswordManager_SendBankCard_Handler,
		},
		{
			MethodName: "RequestLoginPasswordName",
			Handler:    _PasswordManager_RequestLoginPasswordName_Handler,
		},
		{
			MethodName: "RequestLoginPasswordByName",
			Handler:    _PasswordManager_RequestLoginPasswordByName_Handler,
		},
		{
			MethodName: "RequestTextName",
			Handler:    _PasswordManager_RequestTextName_Handler,
		},
		{
			MethodName: "RequestTextByName",
			Handler:    _PasswordManager_RequestTextByName_Handler,
		},
		{
			MethodName: "RequestBankCardName",
			Handler:    _PasswordManager_RequestBankCardName_Handler,
		},
		{
			MethodName: "RequestBankCardByName",
			Handler:    _PasswordManager_RequestBankCardByName_Handler,
		},
		{
			MethodName: "RequestFileName",
			Handler:    _PasswordManager_RequestFileName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LocalBackupFile",
			Handler:       _PasswordManager_LocalBackupFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LocalRestoreFile",
			Handler:       _PasswordManager_LocalRestoreFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendFile",
			Handler:       _PasswordManager_SendFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RequestFileByName",
			Handler:       _PasswordManager_RequestFileByName_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/client.proto",
}
