syntax = "proto3";

import "google/protobuf/empty.proto";

package manager;

option go_package = "github.com/Part001-R/YaPr-GP-2/proto";

service PasswordManager {
    rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty);
    rpc BackupFile(stream UploadRequest) returns (UploadResponse);
    rpc RestoreFile(DownloadRequest) returns (stream DownloadResponse);
    rpc FilesInfo(google.protobuf.Empty) returns (FilesInfoResponse);
}

message UploadRequest {
    string fileName = 1;
    bytes content = 2;
}

message UploadResponse {
    string fileName = 1;
}

message DownloadRequest {
    string fileName = 1;
}

message DownloadResponse {
    string fileName = 1;
    bytes content = 2;
}

message FileInfo {
    string fileName = 1;
    int64 size = 2;
}

message FilesInfoResponse {
    repeated FileInfo fileInfo = 1;
}
