// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/client.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PasswordManager_Ping_FullMethodName              = "/manager.PasswordManager/Ping"
	PasswordManager_BackupFile_FullMethodName        = "/manager.PasswordManager/BackupFile"
	PasswordManager_RestoreFile_FullMethodName       = "/manager.PasswordManager/RestoreFile"
	PasswordManager_FilesInfo_FullMethodName         = "/manager.PasswordManager/FilesInfo"
	PasswordManager_Registration_FullMethodName      = "/manager.PasswordManager/Registration"
	PasswordManager_Authentication_FullMethodName    = "/manager.PasswordManager/Authentication"
	PasswordManager_SendLoginPassword_FullMethodName = "/manager.PasswordManager/SendLoginPassword"
	PasswordManager_SendText_FullMethodName          = "/manager.PasswordManager/SendText"
	PasswordManager_SendBankCard_FullMethodName      = "/manager.PasswordManager/SendBankCard"
	PasswordManager_SendFile_FullMethodName          = "/manager.PasswordManager/SendFile"
)

// PasswordManagerClient is the client API for PasswordManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasswordManagerClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BackupFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
	RestoreFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error)
	FilesInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FilesInfoResponse, error)
	Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Authentication(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
	SendLoginPassword(ctx context.Context, in *SendLoginPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendBankCard(ctx context.Context, in *SendBankCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendFileRequest, SendFileResponse], error)
}

type passwordManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPasswordManagerClient(cc grpc.ClientConnInterface) PasswordManagerClient {
	return &passwordManagerClient{cc}
}

func (c *passwordManagerClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) BackupFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[0], PasswordManager_BackupFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_BackupFileClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

func (c *passwordManagerClient) RestoreFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[1], PasswordManager_RestoreFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_RestoreFileClient = grpc.ServerStreamingClient[DownloadResponse]

func (c *passwordManagerClient) FilesInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FilesInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilesInfoResponse)
	err := c.cc.Invoke(ctx, PasswordManager_FilesInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) Registration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_Registration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) Authentication(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, PasswordManager_Authentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendLoginPassword(ctx context.Context, in *SendLoginPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_SendLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendBankCard(ctx context.Context, in *SendBankCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PasswordManager_SendBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendFileRequest, SendFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PasswordManager_ServiceDesc.Streams[2], PasswordManager_SendFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendFileRequest, SendFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_SendFileClient = grpc.ClientStreamingClient[SendFileRequest, SendFileResponse]

// PasswordManagerServer is the server API for PasswordManager service.
// All implementations must embed UnimplementedPasswordManagerServer
// for forward compatibility.
type PasswordManagerServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	BackupFile(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	RestoreFile(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error
	FilesInfo(context.Context, *emptypb.Empty) (*FilesInfoResponse, error)
	Registration(context.Context, *RegistrationRequest) (*emptypb.Empty, error)
	Authentication(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
	SendLoginPassword(context.Context, *SendLoginPasswordRequest) (*emptypb.Empty, error)
	SendText(context.Context, *SendTextRequest) (*emptypb.Empty, error)
	SendBankCard(context.Context, *SendBankCardRequest) (*emptypb.Empty, error)
	SendFile(grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]) error
	mustEmbedUnimplementedPasswordManagerServer()
}

// UnimplementedPasswordManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPasswordManagerServer struct{}

func (UnimplementedPasswordManagerServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPasswordManagerServer) BackupFile(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method BackupFile not implemented")
}
func (UnimplementedPasswordManagerServer) RestoreFile(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error {
	return status.Error(codes.Unimplemented, "method RestoreFile not implemented")
}
func (UnimplementedPasswordManagerServer) FilesInfo(context.Context, *emptypb.Empty) (*FilesInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilesInfo not implemented")
}
func (UnimplementedPasswordManagerServer) Registration(context.Context, *RegistrationRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Registration not implemented")
}
func (UnimplementedPasswordManagerServer) Authentication(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authentication not implemented")
}
func (UnimplementedPasswordManagerServer) SendLoginPassword(context.Context, *SendLoginPasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendLoginPassword not implemented")
}
func (UnimplementedPasswordManagerServer) SendText(context.Context, *SendTextRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedPasswordManagerServer) SendBankCard(context.Context, *SendBankCardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBankCard not implemented")
}
func (UnimplementedPasswordManagerServer) SendFile(grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]) error {
	return status.Error(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedPasswordManagerServer) mustEmbedUnimplementedPasswordManagerServer() {}
func (UnimplementedPasswordManagerServer) testEmbeddedByValue()                         {}

// UnsafePasswordManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasswordManagerServer will
// result in compilation errors.
type UnsafePasswordManagerServer interface {
	mustEmbedUnimplementedPasswordManagerServer()
}

func RegisterPasswordManagerServer(s grpc.ServiceRegistrar, srv PasswordManagerServer) {
	// If the following call panics, it indicates UnimplementedPasswordManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PasswordManager_ServiceDesc, srv)
}

func _PasswordManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_BackupFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PasswordManagerServer).BackupFile(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_BackupFileServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

func _PasswordManager_RestoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PasswordManagerServer).RestoreFile(m, &grpc.GenericServerStream[DownloadRequest, DownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_RestoreFileServer = grpc.ServerStreamingServer[DownloadResponse]

func _PasswordManager_FilesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).FilesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_FilesInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).FilesInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_Registration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).Registration(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_Authentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).Authentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_Authentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).Authentication(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendLoginPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).SendLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_SendLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).SendLoginPassword(ctx, req.(*SendLoginPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBankCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).SendBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasswordManager_SendBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).SendBankCard(ctx, req.(*SendBankCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_SendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PasswordManagerServer).SendFile(&grpc.GenericServerStream[SendFileRequest, SendFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PasswordManager_SendFileServer = grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]

// PasswordManager_ServiceDesc is the grpc.ServiceDesc for PasswordManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasswordManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager.PasswordManager",
	HandlerType: (*PasswordManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PasswordManager_Ping_Handler,
		},
		{
			MethodName: "FilesInfo",
			Handler:    _PasswordManager_FilesInfo_Handler,
		},
		{
			MethodName: "Registration",
			Handler:    _PasswordManager_Registration_Handler,
		},
		{
			MethodName: "Authentication",
			Handler:    _PasswordManager_Authentication_Handler,
		},
		{
			MethodName: "SendLoginPassword",
			Handler:    _PasswordManager_SendLoginPassword_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _PasswordManager_SendText_Handler,
		},
		{
			MethodName: "SendBankCard",
			Handler:    _PasswordManager_SendBankCard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BackupFile",
			Handler:       _PasswordManager_BackupFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RestoreFile",
			Handler:       _PasswordManager_RestoreFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendFile",
			Handler:       _PasswordManager_SendFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/client.proto",
}
